name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3.3.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Create timestamp.json file
      - name: Create timestamp file
        run: echo "{\"timestamp\":\"$(date +%s)\"}" > timestamp.json

      # Build your Jekyll site (if needed)
      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Adjust this if your output directory is different
          cname: ${{ secrets.CNAME }}  # Optional: if you have a custom domain

      # Add timestamp.json to build artifact
      - name: Add timestamp to build artifact
        uses: actions/upload-artifact@v3
        with:
          name: timestamp
          path: timestamp.json
